name: kweliscore
description: K-Smart
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Apple
  cupertino_icons: ^1.0.1

  flutter_svg:
  # Fonts
  google_fonts: ^2.1.0
  # State management
  provider: ^5.0.0
  # DateFormat
  intl: ^0.17.0
  # Share
  share: ^2.0.4
  # Network
  http: ^0.13.3
  # Connectivity
  connectivity: ^3.0.6
  # Local STorage
  shared_preferences: ^2.0.6
  # Settings
  app_settings: ^4.1.0
  # Firebase
  # ***---REQUIREMENT---***
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  firebase_crashlytics: ^2.0.4
  firebase_analytics: ^8.1.0
  firebase_performance: ^0.7.0+3
  # Spinner
  flutter_spinkit: ^5.0.0
  # Toast
  fluttertoast: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  flutter_launcher_icons: ^0.9.0
  # integration_test:
  #   sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/launcher/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ksmart-logo.png"
  image_path_android: "assets/launcher/ksmart-logo.png"

